name: PetClinic pipeline

on:
  push:
    branches: [ dev ]
  pull_request: [ main ]

permissions:
  contents: read
  id-token: write
  packages: write

env: 
  JAVA_VERSION: '25'
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}


jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0


    - name: Gitleaks Secret Scan
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
