name: PetClinic pipeline

on:
  push:
    branches: [ dev ]
  pull_request: 
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  packages: write

env: 
  JAVA_VERSION: '25'
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID}}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID}}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR}}
  VAULT_JFROG_PATH: secrets/creds/jfrog
  JFOG_URL: ${{ secrets.JF_URL }}
  JFROG_REPO: 'devops-project'
  


jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0


    - name: Gitleaks Secret Scan
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    name: Build
    needs: gitleaks
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
  
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-v${{ github.run_number }}
          path: target/*.jar
          retention-days: 1
  
  tests:
    needs: build
    name: Unit tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Test
        run: mvn -B test

      - name: Upload the test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-v${{ github.run_number }}
          path: target/surefire-reports/
          if-no-files-found: ignore

  sonar:
    runs-on: ubuntu-latest
    steps: 
        
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
        
      - name: Set up JDK ${{env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: SonarQube code analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=target/classes
      - name: Debug Sonar report
        run: cat .scannerwork/report-task.txt

  trivy:
    needs: sonar
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Set up JDK ${{env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
      
      - name: Populate Maven Cache
        run: |
          mvn -B dependency:resolve -DskipTests --no-transfer-progress

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar-v${{ github.run_number }}
          path: target

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: table
          severity: HIGH,CRITICAL
          exit-code: '0' #test pour voir si la pipeline fonctionnne. Normalement 0

      - name: Upload Trivy results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-results.*
          if-no-files-found: ignore
  
  publish:
    needs: [ sonar, trivy ]
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Download the artifaction
        uses: actions/download-artifact@v4
        with:
          name: app-jar-v${{ github.run_number }}
          path: target
      
      - name: Authenticate to Vault & Fecth JFrog credentials
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR}}
          method: approle
          roleId: ${{ env.VAULT_ROLE_ID }}
          secretId: ${{ env.VAULT_SECRET_ID }}
          secrets: |
            ${{ env.VAULT_JFROG_PATH }} username | JF_USER
            ${{ env.VAULT_JFROG_PATH }} password | JF_PASSWORD
            
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JFROG_URL }}
          JF_USER: ${{ env.JF_USER }}
          JF_PASSWORD: ${{ env.JF_PASSWORD }}
    
      - name: Upload JAR to Artifactory
        run: jf rt upload "target/*.jar" ${{ env.JFROG_REPO }}/
  
    
          