name: PetClinic - CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

permissions:
    contents: read
    id-token: write
    packages: write

env:
    JAVA_VERSION: '25'
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
    SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                fetch-depth: 0
      
            - name: Gitleaks scan
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

    build:
        needs: gitleaks
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            
            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ env.JAVA_VERSION }}
                distribution: 'temurin'
                cache: maven
            
            - name: Build the artifact
              run: mvn -B clean package -DskipTests
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: app-jar-v${{ github.run_number}}
                path: target/*.jar
                retention-days: 1
    unitTest:
        needs: build
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            
            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ env.JAVA_VERSION }}
                distribution: 'temurin'
                cache: maven
            
            - name: run Unit test
              run: mvn -B test
            
            - name: Upload the test report
              uses: actions/upload-artifact@v4
              with:
                name: surefire-reports
                path: target/surefire-reports/
                if-no-files-found: ignore
    
    SonarCloud-scan:
        needs: unitTest
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4

            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ env.JAVA_VERSION }}
                distribution: 'temurin'
            
            - name: Cache SonarQube packages
              uses: actions/cache@v4
              with:
                path: ~/.sonar/cache
                key: ${{ runner.os }}-sonar
                restore-keys: ${{ runner.os }}-sonar
            
            - name: Compile the code
              run: mvn -B compile -DskipTests
            
            - name: SonarCloud analysis
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
              with:
                args: >
                    -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
                    -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
                    -Dsonar.java.binaries=target/classes

    trivy-scan-vulnerability:
        needs: SonarCloud-scan
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4

            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ env.JAVA_VERSION }}
                distribution: 'temurin'
            
            - name: Maven dependencies
              run: mvn -B dependency:resolve -DskipTests --no-transfer-progress
    
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: app-jar-v${{ github.run_number}}
                path: target
            
            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: 'table'
                exit-code: '0'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true
            
            - name: Upload the report
              uses: actions/upload-artifact@v4
              with:
                name: trivy-fs-report
                path: trivy-results.*
                if-no-files-found: ignore
            
          